### ISSUE TITLE
Support custom API endpoints in browser

### ISSUE THREAD

**Issue by imathews** [redivis/redivis-js#6]
Currently, we read the the API endpoint from an env variable. Need a way to pass it in when in the browser

**Comment by stevejpurves** [comment]
In addition to passing in the API endpoint, it would also be good to do something with auth. The specific use case I have is we are making calls to the Redivis API via a proxy from the browser. 

The app in the browser is authenticated against it's own API which proxies redivis at `/api/redivis`. The app makes requests to the app API using a Cookie or an Authorization header. So we'd need a was in one case to set the Auth header, and in the other way just make plain fetch calls and fallback on the Cookie based auth.
